package net.minecraft.src;

import net.minecraft.dispenser.BehaviorProjectileDispense;
import net.minecraft.server.dedicated.PendingCommand;
import net.minecraft.util.SoundCategory;

public class qf
{
    public static final SoundCategory a;
    public static final SoundCategory b;
    public static final SoundCategory c;
    public static final SoundCategory d;
    public static final SoundCategory e;
    public static final SoundCategory f;
    public static final SoundCategory g;
    public static final SoundCategory h;
    public static final SoundCategory i;
    public static final SoundCategory j;
    public static final SoundCategory k;
    public static final SoundCategory l;
    public static final SoundCategory m;
    public static final SoundCategory n;
    public static final SoundCategory o;
    public static final SoundCategory p;
    public static final SoundCategory q;
    public static final SoundCategory r;
    public static final SoundCategory s;
    public static final SoundCategory t;
    public static final SoundCategory u;
    public static final SoundCategory v;
    public static final SoundCategory w;
    public static final SoundCategory x;
    public static final SoundCategory y;
    public static final SoundCategory z;
    public static final SoundCategory A;
    public static final SoundCategory B;
    public static final SoundCategory C;
    public static final SoundCategory D;
    public static final SoundCategory E;
    public static final SoundCategory F;
    public static final SoundCategory G;
    public static final SoundCategory H;
    public static final SoundCategory I;
    public static final SoundCategory J;
    public static final SoundCategory K;
    public static final SoundCategory L;
    public static final SoundCategory M;
    public static final SoundCategory N;
    public static final SoundCategory O;
    public static final SoundCategory P;
    public static final SoundCategory Q;
    public static final SoundCategory R;
    public static final SoundCategory S;
    public static final SoundCategory T;
    public static final SoundCategory U;
    public static final SoundCategory V;
    public static final SoundCategory W;
    public static final SoundCategory X;
    public static final SoundCategory Y;
    public static final SoundCategory Z;
    public static final SoundCategory aa;
    public static final SoundCategory ab;
    public static final SoundCategory ac;
    public static final SoundCategory ad;
    public static final SoundCategory ae;
    public static final SoundCategory af;
    public static final SoundCategory ag;
    public static final SoundCategory ah;
    public static final SoundCategory ai;
    public static final SoundCategory aj;
    public static final SoundCategory ak;
    public static final SoundCategory al;
    public static final SoundCategory am;
    public static final SoundCategory an;
    public static final SoundCategory ao;
    public static final SoundCategory ap;
    public static final SoundCategory aq;
    public static final SoundCategory ar;
    public static final SoundCategory as;
    public static final SoundCategory at;
    public static final SoundCategory au;
    public static final SoundCategory av;
    public static final SoundCategory aw;
    public static final SoundCategory ax;
    public static final SoundCategory ay;
    public static final SoundCategory az;
    public static final SoundCategory aA;
    public static final SoundCategory aB;
    public static final SoundCategory aC;
    public static final SoundCategory aD;
    public static final SoundCategory aE;
    public static final SoundCategory aF;
    public static final SoundCategory aG;
    public static final SoundCategory aH;
    public static final SoundCategory aI;
    public static final SoundCategory aJ;
    public static final SoundCategory aK;
    public static final SoundCategory aL;
    public static final SoundCategory aM;
    public static final SoundCategory aN;
    public static final SoundCategory aO;
    public static final SoundCategory aP;
    public static final SoundCategory aQ;
    public static final SoundCategory aR;
    public static final SoundCategory aS;
    public static final SoundCategory aT;
    public static final SoundCategory aU;
    public static final SoundCategory aV;
    public static final SoundCategory aW;
    public static final SoundCategory aX;
    public static final SoundCategory aY;
    public static final SoundCategory aZ;
    public static final SoundCategory ba;
    public static final SoundCategory bb;
    public static final SoundCategory bc;
    public static final SoundCategory bd;
    public static final SoundCategory be;
    public static final SoundCategory bf;
    public static final SoundCategory bg;
    public static final SoundCategory bh;
    public static final SoundCategory bi;
    public static final SoundCategory bj;
    public static final SoundCategory bk;
    public static final SoundCategory bl;
    public static final SoundCategory bm;
    public static final SoundCategory bn;
    public static final SoundCategory bo;
    public static final SoundCategory bp;
    public static final SoundCategory bq;
    public static final SoundCategory br;
    public static final SoundCategory bs;
    public static final SoundCategory bt;
    public static final SoundCategory bu;
    public static final SoundCategory bv;
    public static final SoundCategory bw;
    public static final SoundCategory bx;
    public static final SoundCategory by;
    public static final SoundCategory bz;
    public static final SoundCategory bA;
    public static final SoundCategory bB;
    public static final SoundCategory bC;
    public static final SoundCategory bD;
    public static final SoundCategory bE;
    public static final SoundCategory bF;
    public static final SoundCategory bG;
    public static final SoundCategory bH;
    public static final SoundCategory bI;
    public static final SoundCategory bJ;
    public static final SoundCategory bK;
    public static final SoundCategory bL;
    public static final SoundCategory bM;
    public static final SoundCategory bN;
    public static final SoundCategory bO;
    public static final SoundCategory bP;
    public static final SoundCategory bQ;
    public static final SoundCategory bR;
    public static final SoundCategory bS;
    public static final SoundCategory bT;
    public static final SoundCategory bU;
    public static final SoundCategory bV;
    public static final SoundCategory bW;
    public static final SoundCategory bX;
    public static final SoundCategory bY;
    public static final SoundCategory bZ;
    public static final SoundCategory ca;
    public static final SoundCategory cb;
    public static final SoundCategory cc;
    public static final SoundCategory cd;
    public static final SoundCategory ce;
    public static final SoundCategory cf;
    public static final SoundCategory cg;
    public static final SoundCategory ch;
    public static final SoundCategory ci;
    public static final SoundCategory cj;
    public static final SoundCategory ck;
    public static final SoundCategory cl;
    public static final SoundCategory cm;
    public static final SoundCategory cn;
    public static final SoundCategory co;
    public static final SoundCategory cp;
    public static final SoundCategory cq;
    public static final SoundCategory cr;
    public static final SoundCategory cs;
    public static final SoundCategory ct;
    public static final SoundCategory cu;
    public static final SoundCategory cv;
    public static final SoundCategory cw;
    public static final SoundCategory cx;
    public static final SoundCategory cy;
    public static final SoundCategory cz;
    public static final SoundCategory cA;
    public static final SoundCategory cB;
    public static final SoundCategory cC;
    public static final SoundCategory cD;
    public static final SoundCategory cE;
    public static final SoundCategory cF;
    public static final SoundCategory cG;
    public static final SoundCategory cH;
    public static final SoundCategory cI;
    public static final SoundCategory cJ;
    public static final SoundCategory cK;
    public static final SoundCategory cL;
    public static final SoundCategory cM;
    public static final SoundCategory cN;
    public static final SoundCategory cO;
    public static final SoundCategory cP;
    public static final SoundCategory cQ;
    public static final SoundCategory cR;
    public static final SoundCategory cS;
    public static final SoundCategory cT;
    public static final SoundCategory cU;
    public static final SoundCategory cV;
    public static final SoundCategory cW;
    public static final SoundCategory cX;
    public static final SoundCategory cY;
    public static final SoundCategory cZ;
    public static final SoundCategory da;
    public static final SoundCategory db;
    public static final SoundCategory dc;
    public static final SoundCategory dd;
    public static final SoundCategory de;
    public static final SoundCategory df;
    public static final SoundCategory dg;
    public static final SoundCategory dh;
    public static final SoundCategory di;
    public static final SoundCategory dj;
    public static final SoundCategory dk;
    public static final SoundCategory dl;
    public static final SoundCategory dm;
    public static final SoundCategory dn;

    public static final SoundCategory do;

    public static final SoundCategory dp;
    public static final SoundCategory dq;
    public static final SoundCategory dr;
    public static final SoundCategory ds;
    public static final SoundCategory dt;
    public static final SoundCategory du;
    public static final SoundCategory dv;
    public static final SoundCategory dw;
    public static final SoundCategory dx;
    public static final SoundCategory dy;
    public static final SoundCategory dz;
    public static final SoundCategory dA;
    public static final SoundCategory dB;
    public static final SoundCategory dC;
    public static final SoundCategory dD;
    public static final SoundCategory dE;
    public static final SoundCategory dF;
    public static final SoundCategory dG;
    public static final SoundCategory dH;
    public static final SoundCategory dI;
    public static final SoundCategory dJ;
    public static final SoundCategory dK;
    public static final SoundCategory dL;
    public static final SoundCategory dM;
    public static final SoundCategory dN;
    public static final SoundCategory dO;
    public static final SoundCategory dP;
    public static final SoundCategory dQ;
    public static final SoundCategory dR;
    public static final SoundCategory dS;
    public static final SoundCategory dT;
    public static final SoundCategory dU;
    public static final SoundCategory dV;
    public static final SoundCategory dW;
    public static final SoundCategory dX;
    public static final SoundCategory dY;
    public static final SoundCategory dZ;
    public static final SoundCategory ea;
    public static final SoundCategory eb;
    public static final SoundCategory ec;
    public static final SoundCategory ed;
    public static final SoundCategory ee;
    public static final SoundCategory ef;
    public static final SoundCategory eg;
    public static final SoundCategory eh;
    public static final SoundCategory ei;
    public static final SoundCategory ej;
    public static final SoundCategory ek;
    public static final SoundCategory el;
    public static final SoundCategory em;
    public static final SoundCategory en;
    public static final SoundCategory eo;
    public static final SoundCategory ep;
    public static final SoundCategory eq;
    public static final SoundCategory er;
    public static final SoundCategory es;
    public static final SoundCategory et;
    public static final SoundCategory eu;
    public static final SoundCategory ev;
    public static final SoundCategory ew;
    public static final SoundCategory ex;
    public static final SoundCategory ey;
    public static final SoundCategory ez;
    public static final SoundCategory eA;
    public static final SoundCategory eB;
    public static final SoundCategory eC;
    public static final SoundCategory eD;
    public static final SoundCategory eE;
    public static final SoundCategory eF;
    public static final SoundCategory eG;
    public static final SoundCategory eH;
    public static final SoundCategory eI;
    public static final SoundCategory eJ;
    public static final SoundCategory eK;
    public static final SoundCategory eL;
    public static final SoundCategory eM;
    public static final SoundCategory eN;
    public static final SoundCategory eO;
    public static final SoundCategory eP;
    public static final SoundCategory eQ;
    public static final SoundCategory eR;
    public static final SoundCategory eS;
    public static final SoundCategory eT;
    public static final SoundCategory eU;
    public static final SoundCategory eV;
    public static final SoundCategory eW;
    public static final SoundCategory eX;
    public static final SoundCategory eY;
    public static final SoundCategory eZ;
    public static final SoundCategory fa;
    public static final SoundCategory fb;
    public static final SoundCategory fc;
    public static final SoundCategory fd;
    public static final SoundCategory fe;
    public static final SoundCategory ff;
    public static final SoundCategory fg;
    public static final SoundCategory fh;
    public static final SoundCategory fi;
    public static final SoundCategory fj;
    public static final SoundCategory fk;
    public static final SoundCategory fl;
    public static final SoundCategory fm;
    public static final SoundCategory fn;
    public static final SoundCategory fo;
    public static final SoundCategory fp;
    public static final SoundCategory fq;
    public static final SoundCategory fr;
    public static final SoundCategory fs;
    public static final SoundCategory ft;
    public static final SoundCategory fu;
    public static final SoundCategory fv;
    public static final SoundCategory fw;
    public static final SoundCategory fx;
    public static final SoundCategory fy;
    public static final SoundCategory fz;
    public static final SoundCategory fA;
    public static final SoundCategory fB;
    public static final SoundCategory fC;
    public static final SoundCategory fD;
    public static final SoundCategory fE;
    public static final SoundCategory fF;
    public static final SoundCategory fG;
    public static final SoundCategory fH;
    public static final SoundCategory fI;
    public static final SoundCategory fJ;
    public static final SoundCategory fK;
    public static final SoundCategory fL;
    public static final SoundCategory fM;
    public static final SoundCategory fN;
    public static final SoundCategory fO;
    public static final SoundCategory fP;
    public static final SoundCategory fQ;
    public static final SoundCategory fR;
    public static final SoundCategory fS;
    public static final SoundCategory fT;
    public static final SoundCategory fU;
    public static final SoundCategory fV;
    public static final SoundCategory fW;
    public static final SoundCategory fX;
    public static final SoundCategory fY;
    public static final SoundCategory fZ;
    public static final SoundCategory ga;
    public static final SoundCategory gb;
    public static final SoundCategory gc;
    public static final SoundCategory gd;
    public static final SoundCategory ge;
    public static final SoundCategory gf;
    public static final SoundCategory gg;
    public static final SoundCategory gh;
    public static final SoundCategory gi;
    public static final SoundCategory gj;
    public static final SoundCategory gk;
    public static final SoundCategory gl;
    public static final SoundCategory gm;
    public static final SoundCategory gn;
    public static final SoundCategory go;
    public static final SoundCategory gp;
    public static final SoundCategory gq;
    public static final SoundCategory gr;
    public static final SoundCategory gs;
    public static final SoundCategory gt;
    public static final SoundCategory gu;
    public static final SoundCategory gv;
    public static final SoundCategory gw;
    public static final SoundCategory gx;
    public static final SoundCategory gy;
    public static final SoundCategory gz;
    public static final SoundCategory gA;
    public static final SoundCategory gB;
    public static final SoundCategory gC;
    public static final SoundCategory gD;
    public static final SoundCategory gE;
    public static final SoundCategory gF;
    public static final SoundCategory gG;
    public static final SoundCategory gH;
    public static final SoundCategory gI;
    public static final SoundCategory gJ;
    public static final SoundCategory gK;
    public static final SoundCategory gL;
    public static final SoundCategory gM;
    public static final SoundCategory gN;
    public static final SoundCategory gO;
    public static final SoundCategory gP;
    public static final SoundCategory gQ;
    public static final SoundCategory gR;
    public static final SoundCategory gS;
    public static final SoundCategory gT;
    public static final SoundCategory gU;
    public static final SoundCategory gV;
    public static final SoundCategory gW;
    public static final SoundCategory gX;
    public static final SoundCategory gY;
    public static final SoundCategory gZ;
    public static final SoundCategory ha;
    public static final SoundCategory hb;
    public static final SoundCategory hc;
    public static final SoundCategory hd;
    public static final SoundCategory he;
    public static final SoundCategory hf;
    public static final SoundCategory hg;
    public static final SoundCategory hh;
    public static final SoundCategory hi;
    public static final SoundCategory hj;
    public static final SoundCategory hk;
    public static final SoundCategory hl;
    public static final SoundCategory hm;
    public static final SoundCategory hn;
    public static final SoundCategory ho;
    public static final SoundCategory hp;
    public static final SoundCategory hq;
    public static final SoundCategory hr;
    public static final SoundCategory hs;
    public static final SoundCategory ht;
    public static final SoundCategory hu;
    public static final SoundCategory hv;
    public static final SoundCategory hw;
    public static final SoundCategory hx;
    public static final SoundCategory hy;
    public static final SoundCategory hz;
    public static final SoundCategory hA;
    public static final SoundCategory hB;
    public static final SoundCategory hC;
    public static final SoundCategory hD;
    public static final SoundCategory hE;
    public static final SoundCategory hF;
    public static final SoundCategory hG;
    public static final SoundCategory hH;
    public static final SoundCategory hI;
    public static final SoundCategory hJ;
    public static final SoundCategory hK;
    public static final SoundCategory hL;
    public static final SoundCategory hM;
    public static final SoundCategory hN;
    public static final SoundCategory hO;
    public static final SoundCategory hP;
    public static final SoundCategory hQ;
    public static final SoundCategory hR;
    public static final SoundCategory hS;
    public static final SoundCategory hT;
    public static final SoundCategory hU;
    public static final SoundCategory hV;
    public static final SoundCategory hW;
    public static final SoundCategory hX;
    public static final SoundCategory hY;
    public static final SoundCategory hZ;
    public static final SoundCategory ia;
    public static final SoundCategory ib;
    public static final SoundCategory ic;
    public static final SoundCategory id;
    public static final SoundCategory ie;

    public static final SoundCategory if ;

public static final SoundCategory ig;
public static final SoundCategory ih;
public static final SoundCategory ii;
public static final SoundCategory ij;
public static final SoundCategory ik;
public static final SoundCategory il;
public static final SoundCategory im;
public static final SoundCategory in;
public static final SoundCategory io;
public static final SoundCategory ip;
public static final SoundCategory iq;
public static final SoundCategory ir;
public static final SoundCategory is;
public static final SoundCategory it;
public static final SoundCategory iu;
public static final SoundCategory iv;
public static final SoundCategory iw;
public static final SoundCategory ix;
public static final SoundCategory iy;
public static final SoundCategory iz;
public static final SoundCategory iA;
public static final SoundCategory iB;
public static final SoundCategory iC;
public static final SoundCategory iD;
public static final SoundCategory iE;
public static final SoundCategory iF;
public static final SoundCategory iG;
public static final SoundCategory iH;
public static final SoundCategory iI;
public static final SoundCategory iJ;
public static final SoundCategory iK;
public static final SoundCategory iL;
public static final SoundCategory iM;
public static final SoundCategory iN;
public static final SoundCategory iO;
public static final SoundCategory iP;
public static final SoundCategory iQ;
public static final SoundCategory iR;
public static final SoundCategory iS;
public static final SoundCategory iT;
public static final SoundCategory iU;
public static final SoundCategory iV;
public static final SoundCategory iW;
public static final SoundCategory iX;
public static final SoundCategory iY;
public static final SoundCategory iZ;
public static final SoundCategory ja;
public static final SoundCategory jb;
public static final SoundCategory jc;
public static final SoundCategory jd;
public static final SoundCategory je;
public static final SoundCategory jf;
public static final SoundCategory jg;
public static final SoundCategory jh;
public static final SoundCategory ji;
public static final SoundCategory jj;
public static final SoundCategory jk;
public static final SoundCategory jl;
public static final SoundCategory jm;
public static final SoundCategory jn;
public static final SoundCategory jo;
public static final SoundCategory jp;
public static final SoundCategory jq;
public static final SoundCategory jr;
public static final SoundCategory js;
public static final SoundCategory jt;
public static final SoundCategory ju;
public static final SoundCategory jv;
public static final SoundCategory jw;
public static final SoundCategory jx;
public static final SoundCategory jy;
public static final SoundCategory jz;
public static final SoundCategory jA;
public static final SoundCategory jB;
public static final SoundCategory jC;

private static SoundCategory a(String p_a_0_)
    {
        SoundCategory soundcategory = SoundCategory.MASTER.getObject(new BehaviorProjectileDispense(p_a_0_));

        if (soundcategory == null)
        {
            throw new IllegalStateException("Invalid Sound requested: " + p_a_0_);
        }
        else
        {
            return soundcategory;
        }
    }

    static
    {
        if (!PendingCommand.a())
        {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        }
        else
        {
            a = a("ambient.cave");
            b = a("block.anvil.break");
            c = a("block.anvil.destroy");
            d = a("block.anvil.fall");
            e = a("block.anvil.hit");
            f = a("block.anvil.land");
            g = a("block.anvil.place");
            h = a("block.anvil.step");
            i = a("block.anvil.use");
            j = a("entity.armorstand.break");
            k = a("entity.armorstand.fall");
            l = a("entity.armorstand.hit");
            m = a("entity.armorstand.place");
            n = a("item.armor.equip_chain");
            o = a("item.armor.equip_diamond");
            p = a("item.armor.equip_elytra");
            q = a("item.armor.equip_generic");
            r = a("item.armor.equip_gold");
            s = a("item.armor.equip_iron");
            t = a("item.armor.equip_leather");
            u = a("entity.arrow.hit");
            v = a("entity.arrow.hit_player");
            w = a("entity.arrow.shoot");
            x = a("entity.bat.ambient");
            y = a("entity.bat.death");
            z = a("entity.bat.hurt");
            A = a("entity.bat.loop");
            B = a("entity.bat.takeoff");
            C = a("entity.blaze.ambient");
            D = a("entity.blaze.burn");
            E = a("entity.blaze.death");
            F = a("entity.blaze.hurt");
            G = a("entity.blaze.shoot");
            H = a("entity.boat.paddle_land");
            I = a("entity.boat.paddle_water");
            J = a("entity.bobber.retrieve");
            K = a("entity.bobber.splash");
            L = a("entity.bobber.throw");
            M = a("item.bottle.empty");
            N = a("item.bottle.fill");
            O = a("item.bottle.fill_dragonbreath");
            P = a("block.brewing_stand.brew");
            Q = a("item.bucket.empty");
            R = a("item.bucket.empty_lava");
            S = a("item.bucket.fill");
            T = a("item.bucket.fill_lava");
            U = a("entity.cat.ambient");
            V = a("entity.cat.death");
            W = a("entity.cat.hiss");
            X = a("entity.cat.hurt");
            Y = a("entity.cat.purr");
            Z = a("entity.cat.purreow");
            aa = a("block.chest.close");
            ab = a("block.chest.locked");
            ac = a("block.chest.open");
            ad = a("entity.chicken.ambient");
            ae = a("entity.chicken.death");
            af = a("entity.chicken.egg");
            ag = a("entity.chicken.hurt");
            ah = a("entity.chicken.step");
            ai = a("block.chorus_flower.death");
            aj = a("block.chorus_flower.grow");
            ak = a("item.chorus_fruit.teleport");
            al = a("block.cloth.break");
            am = a("block.cloth.fall");
            an = a("block.cloth.hit");
            ao = a("block.cloth.place");
            ap = a("block.cloth.step");
            aq = a("block.comparator.click");
            ar = a("entity.cow.ambient");
            as = a("entity.cow.death");
            at = a("entity.cow.hurt");
            au = a("entity.cow.milk");
            av = a("entity.cow.step");
            aw = a("entity.creeper.death");
            ax = a("entity.creeper.hurt");
            ay = a("entity.creeper.primed");
            az = a("block.dispenser.dispense");
            aA = a("block.dispenser.fail");
            aB = a("block.dispenser.launch");
            aC = a("entity.donkey.ambient");
            aD = a("entity.donkey.angry");
            aE = a("entity.donkey.chest");
            aF = a("entity.donkey.death");
            aG = a("entity.donkey.hurt");
            aH = a("entity.egg.throw");
            aI = a("entity.elder_guardian.ambient");
            aJ = a("entity.elder_guardian.ambient_land");
            aK = a("entity.elder_guardian.curse");
            aL = a("entity.elder_guardian.death");
            aM = a("entity.elder_guardian.death_land");
            aN = a("entity.elder_guardian.flop");
            aO = a("entity.elder_guardian.hurt");
            aP = a("entity.elder_guardian.hurt_land");
            aQ = a("item.elytra.flying");
            aR = a("block.enchantment_table.use");
            aS = a("block.enderchest.close");
            aT = a("block.enderchest.open");
            aU = a("entity.enderdragon.ambient");
            aV = a("entity.enderdragon.death");
            aW = a("entity.enderdragon_fireball.explode");
            aX = a("entity.enderdragon.flap");
            aY = a("entity.enderdragon.growl");
            aZ = a("entity.enderdragon.hurt");
            ba = a("entity.enderdragon.shoot");
            bb = a("entity.endereye.death");
            bc = a("entity.endereye.launch");
            bd = a("entity.endermen.ambient");
            be = a("entity.endermen.death");
            bf = a("entity.endermen.hurt");
            bg = a("entity.endermen.scream");
            bh = a("entity.endermen.stare");
            bi = a("entity.endermen.teleport");
            bj = a("entity.endermite.ambient");
            bk = a("entity.endermite.death");
            bl = a("entity.endermite.hurt");
            bm = a("entity.endermite.step");
            bn = a("entity.enderpearl.throw");
            bo = a("block.end_gateway.spawn");
            bp = a("block.end_portal_frame.fill");
            bq = a("block.end_portal.spawn");
            br = a("entity.evocation_fangs.attack");
            bs = a("entity.evocation_illager.ambient");
            bt = a("entity.evocation_illager.cast_spell");
            bu = a("entity.evocation_illager.death");
            bv = a("entity.evocation_illager.hurt");
            bw = a("entity.evocation_illager.prepare_attack");
            bx = a("entity.evocation_illager.prepare_summon");
            by = a("entity.evocation_illager.prepare_wololo");
            bz = a("entity.experience_bottle.throw");
            bA = a("entity.experience_orb.pickup");
            bB = a("block.fence_gate.close");
            bC = a("block.fence_gate.open");
            bD = a("item.firecharge.use");
            bE = a("entity.firework.blast");
            bF = a("entity.firework.blast_far");
            bG = a("entity.firework.large_blast");
            bH = a("entity.firework.large_blast_far");
            bI = a("entity.firework.launch");
            bJ = a("entity.firework.shoot");
            bK = a("entity.firework.twinkle");
            bL = a("entity.firework.twinkle_far");
            bM = a("block.fire.ambient");
            bN = a("block.fire.extinguish");
            bO = a("item.flintandsteel.use");
            bP = a("block.furnace.fire_crackle");
            bQ = a("entity.generic.big_fall");
            bR = a("entity.generic.burn");
            bS = a("entity.generic.death");
            bT = a("entity.generic.drink");
            bU = a("entity.generic.eat");
            bV = a("entity.generic.explode");
            bW = a("entity.generic.extinguish_fire");
            bX = a("entity.generic.hurt");
            bY = a("entity.generic.small_fall");
            bZ = a("entity.generic.splash");
            ca = a("entity.generic.swim");
            cb = a("entity.ghast.ambient");
            cc = a("entity.ghast.death");
            cd = a("entity.ghast.hurt");
            ce = a("entity.ghast.scream");
            cf = a("entity.ghast.shoot");
            cg = a("entity.ghast.warn");
            ch = a("block.glass.break");
            ci = a("block.glass.fall");
            cj = a("block.glass.hit");
            ck = a("block.glass.place");
            cl = a("block.glass.step");
            cm = a("block.grass.break");
            cn = a("block.grass.fall");
            co = a("block.grass.hit");
            cp = a("block.grass.place");
            cq = a("block.grass.step");
            cr = a("block.gravel.break");
            cs = a("block.gravel.fall");
            ct = a("block.gravel.hit");
            cu = a("block.gravel.place");
            cv = a("block.gravel.step");
            cw = a("entity.guardian.ambient");
            cx = a("entity.guardian.ambient_land");
            cy = a("entity.guardian.attack");
            cz = a("entity.guardian.death");
            cA = a("entity.guardian.death_land");
            cB = a("entity.guardian.flop");
            cC = a("entity.guardian.hurt");
            cD = a("entity.guardian.hurt_land");
            cE = a("item.hoe.till");
            cF = a("entity.horse.ambient");
            cG = a("entity.horse.angry");
            cH = a("entity.horse.armor");
            cI = a("entity.horse.breathe");
            cJ = a("entity.horse.death");
            cK = a("entity.horse.eat");
            cL = a("entity.horse.gallop");
            cM = a("entity.horse.hurt");
            cN = a("entity.horse.jump");
            cO = a("entity.horse.land");
            cP = a("entity.horse.saddle");
            cQ = a("entity.horse.step");
            cR = a("entity.horse.step_wood");
            cS = a("entity.hostile.big_fall");
            cT = a("entity.hostile.death");
            cU = a("entity.hostile.hurt");
            cV = a("entity.hostile.small_fall");
            cW = a("entity.hostile.splash");
            cX = a("entity.hostile.swim");
            cY = a("entity.husk.ambient");
            cZ = a("entity.husk.death");
            da = a("entity.husk.hurt");
            db = a("entity.husk.step");
            dc = a("entity.illusion_illager.ambient");
            dd = a("entity.illusion_illager.cast_spell");
            de = a("entity.illusion_illager.death");
            df = a("entity.illusion_illager.hurt");
            dg = a("entity.illusion_illager.mirror_move");
            dh = a("entity.illusion_illager.prepare_blindness");
            di = a("entity.illusion_illager.prepare_mirror");
            dj = a("entity.irongolem.attack");
            dk = a("entity.irongolem.death");
            dl = a("entity.irongolem.hurt");
            dm = a("entity.irongolem.step");
            dn = a("block.iron_door.close");

            do
            {
                    = a("block.iron_door.open");
            }

            dp = a("block.iron_trapdoor.close");
            dq = a("block.iron_trapdoor.open");
            dr = a("entity.itemframe.add_item");
            ds = a("entity.itemframe.break");
            dt = a("entity.itemframe.place");
            du = a("entity.itemframe.remove_item");
            dv = a("entity.itemframe.rotate_item");
            dw = a("entity.item.break");
            dx = a("entity.item.pickup");
            dy = a("block.ladder.break");
            dz = a("block.ladder.fall");
            dA = a("block.ladder.hit");
            dB = a("block.ladder.place");
            dC = a("block.ladder.step");
            dD = a("block.lava.ambient");
            dE = a("block.lava.extinguish");
            dF = a("block.lava.pop");
            dG = a("entity.leashknot.break");
            dH = a("entity.leashknot.place");
            dI = a("block.lever.click");
            dJ = a("entity.lightning.impact");
            dK = a("entity.lightning.thunder");
            dL = a("entity.lingeringpotion.throw");
            dM = a("entity.llama.ambient");
            dN = a("entity.llama.angry");
            dO = a("entity.llama.chest");
            dP = a("entity.llama.death");
            dQ = a("entity.llama.eat");
            dR = a("entity.llama.hurt");
            dS = a("entity.llama.spit");
            dT = a("entity.llama.step");
            dU = a("entity.llama.swag");
            dV = a("entity.magmacube.death");
            dW = a("entity.magmacube.hurt");
            dX = a("entity.magmacube.jump");
            dY = a("entity.magmacube.squish");
            dZ = a("block.metal.break");
            ea = a("block.metal.fall");
            eb = a("block.metal.hit");
            ec = a("block.metal.place");
            ed = a("block.metal_pressureplate.click_off");
            ee = a("block.metal_pressureplate.click_on");
            ef = a("block.metal.step");
            eg = a("entity.minecart.inside");
            eh = a("entity.minecart.riding");
            ei = a("entity.mooshroom.shear");
            ej = a("entity.mule.ambient");
            ek = a("entity.mule.chest");
            el = a("entity.mule.death");
            em = a("entity.mule.hurt");
            en = a("music.creative");
            eo = a("music.credits");
            ep = a("music.dragon");
            eq = a("music.end");
            er = a("music.game");
            es = a("music.menu");
            et = a("music.nether");
            eu = a("block.note.basedrum");
            ev = a("block.note.bass");
            ew = a("block.note.bell");
            ex = a("block.note.chime");
            ey = a("block.note.flute");
            ez = a("block.note.guitar");
            eA = a("block.note.harp");
            eB = a("block.note.hat");
            eC = a("block.note.pling");
            eD = a("block.note.snare");
            eE = a("block.note.xylophone");
            eF = a("entity.painting.break");
            eG = a("entity.painting.place");
            eH = a("entity.parrot.ambient");
            eI = a("entity.parrot.death");
            eJ = a("entity.parrot.eat");
            eK = a("entity.parrot.fly");
            eL = a("entity.parrot.hurt");
            eM = a("entity.parrot.imitate.blaze");
            eN = a("entity.parrot.imitate.creeper");
            eO = a("entity.parrot.imitate.elder_guardian");
            eP = a("entity.parrot.imitate.enderdragon");
            eQ = a("entity.parrot.imitate.enderman");
            eR = a("entity.parrot.imitate.endermite");
            eS = a("entity.parrot.imitate.evocation_illager");
            eT = a("entity.parrot.imitate.ghast");
            eU = a("entity.parrot.imitate.husk");
            eV = a("entity.parrot.imitate.illusion_illager");
            eW = a("entity.parrot.imitate.magmacube");
            eX = a("entity.parrot.imitate.polar_bear");
            eY = a("entity.parrot.imitate.shulker");
            eZ = a("entity.parrot.imitate.silverfish");
            fa = a("entity.parrot.imitate.skeleton");
            fb = a("entity.parrot.imitate.slime");
            fc = a("entity.parrot.imitate.spider");
            fd = a("entity.parrot.imitate.stray");
            fe = a("entity.parrot.imitate.vex");
            ff = a("entity.parrot.imitate.vindication_illager");
            fg = a("entity.parrot.imitate.witch");
            fh = a("entity.parrot.imitate.wither");
            fi = a("entity.parrot.imitate.wither_skeleton");
            fj = a("entity.parrot.imitate.wolf");
            fk = a("entity.parrot.imitate.zombie");
            fl = a("entity.parrot.imitate.zombie_pigman");
            fm = a("entity.parrot.imitate.zombie_villager");
            fn = a("entity.parrot.step");
            fo = a("entity.pig.ambient");
            fp = a("entity.pig.death");
            fq = a("entity.pig.hurt");
            fr = a("entity.pig.saddle");
            fs = a("entity.pig.step");
            ft = a("block.piston.contract");
            fu = a("block.piston.extend");
            fv = a("entity.player.attack.crit");
            fw = a("entity.player.attack.knockback");
            fx = a("entity.player.attack.nodamage");
            fy = a("entity.player.attack.strong");
            fz = a("entity.player.attack.sweep");
            fA = a("entity.player.attack.weak");
            fB = a("entity.player.big_fall");
            fC = a("entity.player.breath");
            fD = a("entity.player.burp");
            fE = a("entity.player.death");
            fF = a("entity.player.hurt");
            fG = a("entity.player.hurt_drown");
            fH = a("entity.player.hurt_on_fire");
            fI = a("entity.player.levelup");
            fJ = a("entity.player.small_fall");
            fK = a("entity.player.splash");
            fL = a("entity.player.swim");
            fM = a("entity.polar_bear.ambient");
            fN = a("entity.polar_bear.baby_ambient");
            fO = a("entity.polar_bear.death");
            fP = a("entity.polar_bear.hurt");
            fQ = a("entity.polar_bear.step");
            fR = a("entity.polar_bear.warning");
            fS = a("block.portal.ambient");
            fT = a("block.portal.travel");
            fU = a("block.portal.trigger");
            fV = a("entity.rabbit.ambient");
            fW = a("entity.rabbit.attack");
            fX = a("entity.rabbit.death");
            fY = a("entity.rabbit.hurt");
            fZ = a("entity.rabbit.jump");
            ga = a("record.11");
            gb = a("record.13");
            gc = a("record.blocks");
            gd = a("record.cat");
            ge = a("record.chirp");
            gf = a("record.far");
            gg = a("record.mall");
            gh = a("record.mellohi");
            gi = a("record.stal");
            gj = a("record.strad");
            gk = a("record.wait");
            gl = a("record.ward");
            gm = a("block.redstone_torch.burnout");
            gn = a("block.sand.break");
            go = a("block.sand.fall");
            gp = a("block.sand.hit");
            gq = a("block.sand.place");
            gr = a("block.sand.step");
            gs = a("entity.sheep.ambient");
            gt = a("entity.sheep.death");
            gu = a("entity.sheep.hurt");
            gv = a("entity.sheep.shear");
            gw = a("entity.sheep.step");
            gx = a("item.shield.block");
            gy = a("item.shield.break");
            gz = a("item.shovel.flatten");
            gA = a("entity.shulker.ambient");
            gB = a("block.shulker_box.close");
            gC = a("block.shulker_box.open");
            gD = a("entity.shulker_bullet.hit");
            gE = a("entity.shulker_bullet.hurt");
            gF = a("entity.shulker.close");
            gG = a("entity.shulker.death");
            gH = a("entity.shulker.hurt");
            gI = a("entity.shulker.hurt_closed");
            gJ = a("entity.shulker.open");
            gK = a("entity.shulker.shoot");
            gL = a("entity.shulker.teleport");
            gM = a("entity.silverfish.ambient");
            gN = a("entity.silverfish.death");
            gO = a("entity.silverfish.hurt");
            gP = a("entity.silverfish.step");
            gQ = a("entity.skeleton.ambient");
            gR = a("entity.skeleton.death");
            gS = a("entity.skeleton_horse.ambient");
            gT = a("entity.skeleton_horse.death");
            gU = a("entity.skeleton_horse.hurt");
            gV = a("entity.skeleton.hurt");
            gW = a("entity.skeleton.shoot");
            gX = a("entity.skeleton.step");
            gY = a("entity.slime.attack");
            gZ = a("block.slime.break");
            ha = a("entity.slime.death");
            hb = a("block.slime.fall");
            hc = a("block.slime.hit");
            hd = a("entity.slime.hurt");
            he = a("entity.slime.jump");
            hf = a("block.slime.place");
            hg = a("entity.slime.squish");
            hh = a("block.slime.step");
            hi = a("entity.small_magmacube.death");
            hj = a("entity.small_magmacube.hurt");
            hk = a("entity.small_magmacube.squish");
            hl = a("entity.small_slime.death");
            hm = a("entity.small_slime.hurt");
            hn = a("entity.small_slime.jump");
            ho = a("entity.small_slime.squish");
            hp = a("entity.snowball.throw");
            hq = a("entity.snowman.ambient");
            hr = a("entity.snowman.death");
            hs = a("entity.snowman.hurt");
            ht = a("entity.snowman.shoot");
            hu = a("block.snow.break");
            hv = a("block.snow.fall");
            hw = a("block.snow.hit");
            hx = a("block.snow.place");
            hy = a("block.snow.step");
            hz = a("entity.spider.ambient");
            hA = a("entity.spider.death");
            hB = a("entity.spider.hurt");
            hC = a("entity.spider.step");
            hD = a("entity.splash_potion.break");
            hE = a("entity.splash_potion.throw");
            hF = a("entity.squid.ambient");
            hG = a("entity.squid.death");
            hH = a("entity.squid.hurt");
            hI = a("block.stone.break");
            hJ = a("block.stone_button.click_off");
            hK = a("block.stone_button.click_on");
            hL = a("block.stone.fall");
            hM = a("block.stone.hit");
            hN = a("block.stone.place");
            hO = a("block.stone_pressureplate.click_off");
            hP = a("block.stone_pressureplate.click_on");
            hQ = a("block.stone.step");
            hR = a("entity.stray.ambient");
            hS = a("entity.stray.death");
            hT = a("entity.stray.hurt");
            hU = a("entity.stray.step");
            hV = a("enchant.thorns.hit");
            hW = a("entity.tnt.primed");
            hX = a("item.totem.use");
            hY = a("block.tripwire.attach");
            hZ = a("block.tripwire.click_off");
            ia = a("block.tripwire.click_on");
            ib = a("block.tripwire.detach");
            ic = a("ui.button.click");
            id = a("ui.toast.in");
            ie = a("ui.toast.out");

            if = a("ui.toast.challenge_complete");

            ig = a("entity.vex.ambient");
            ih = a("entity.vex.charge");
            ii = a("entity.vex.death");
            ij = a("entity.vex.hurt");
            ik = a("entity.villager.ambient");
            il = a("entity.villager.death");
            im = a("entity.villager.hurt");
            in = a("entity.villager.no");
            io = a("entity.villager.trading");
            ip = a("entity.villager.yes");
            iq = a("entity.vindication_illager.ambient");
            ir = a("entity.vindication_illager.death");
            is = a("entity.vindication_illager.hurt");
            it = a("block.waterlily.place");
            iu = a("block.water.ambient");
            iv = a("weather.rain");
            iw = a("weather.rain.above");
            ix = a("entity.witch.ambient");
            iy = a("entity.witch.death");
            iz = a("entity.witch.drink");
            iA = a("entity.witch.hurt");
            iB = a("entity.witch.throw");
            iC = a("entity.wither.ambient");
            iD = a("entity.wither.break_block");
            iE = a("entity.wither.death");
            iF = a("entity.wither.hurt");
            iG = a("entity.wither.shoot");
            iH = a("entity.wither_skeleton.ambient");
            iI = a("entity.wither_skeleton.death");
            iJ = a("entity.wither_skeleton.hurt");
            iK = a("entity.wither_skeleton.step");
            iL = a("entity.wither.spawn");
            iM = a("entity.wolf.ambient");
            iN = a("entity.wolf.death");
            iO = a("entity.wolf.growl");
            iP = a("entity.wolf.howl");
            iQ = a("entity.wolf.hurt");
            iR = a("entity.wolf.pant");
            iS = a("entity.wolf.shake");
            iT = a("entity.wolf.step");
            iU = a("entity.wolf.whine");
            iV = a("block.wooden_door.close");
            iW = a("block.wooden_door.open");
            iX = a("block.wooden_trapdoor.close");
            iY = a("block.wooden_trapdoor.open");
            iZ = a("block.wood.break");
            ja = a("block.wood_button.click_off");
            jb = a("block.wood_button.click_on");
            jc = a("block.wood.fall");
            jd = a("block.wood.hit");
            je = a("block.wood.place");
            jf = a("block.wood_pressureplate.click_off");
            jg = a("block.wood_pressureplate.click_on");
            jh = a("block.wood.step");
            ji = a("entity.zombie.ambient");
            jj = a("entity.zombie.attack_door_wood");
            jk = a("entity.zombie.attack_iron_door");
            jl = a("entity.zombie.break_door_wood");
            jm = a("entity.zombie.death");
            jn = a("entity.zombie_horse.ambient");
            jo = a("entity.zombie_horse.death");
            jp = a("entity.zombie_horse.hurt");
            jq = a("entity.zombie.hurt");
            jr = a("entity.zombie.infect");
            js = a("entity.zombie_pig.ambient");
            jt = a("entity.zombie_pig.angry");
            ju = a("entity.zombie_pig.death");
            jv = a("entity.zombie_pig.hurt");
            jw = a("entity.zombie.step");
            jx = a("entity.zombie_villager.ambient");
            jy = a("entity.zombie_villager.converted");
            jz = a("entity.zombie_villager.cure");
            jA = a("entity.zombie_villager.death");
            jB = a("entity.zombie_villager.hurt");
            jC = a("entity.zombie_villager.step");
        }
    }
}
